In [1]:
import numpy as np
import pandas as pd
import scipy
from gym import error, spaces, utils
import joblib as jb
import random


In [2]:
#Creando los 10 features y las constantes necesarias
features=['A','B','C','D','F','G','H','I','j','k']
n_states=len(features)
n_actions=500
e = 0.9 # greedy factor
a= 0.1  # learning rate
g= 0.9 # discount factor
max_episodes = 3 # maximum episodes
fresh_time= 0.3 # fresh time for one move

In [3]:
model=jb.load('rfDefense2021.sav')
print(model)

RandomForestClassifier(max_depth=50, n_estimators=250, random_state=45)


In [4]:
#tabla de pandas
df=pd.DataFrame(columns=features)
print(df)

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []


In [5]:
df

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []

In [8]:
model.predict([[-391, -715,  -15,  -27,   50,    3,  -24,    2,  -86, -141]])

array(['benign'], dtype=object)

In [9]:



def generateValues(malwItems):
    a=0
    while a<malwItems:
        
        valuesToTest=np.array([])
        result=None
        for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-100,100))
                    
        try:
             result=model.predict(valuesToTest.reshape(1,-1))
             result=np.array2string(result)
             print(valuesToTest.reshape(1,-1))
        except Exception as ex:
           pass 
        
        if result=="['malicious']":
            formatier=valuesToTest.reshape(1,-1)[0]
            df.loc[a]=formatier
            a=a+1
            print(result)
       

In [10]:
generateValues(500)

[[ 60. -22.   1. -53. -82.  33. -30.  93. -73. -40.]]
[[-64.  97.  25.  73.  91.  33.  44.   1.  69.  97.]]
[[-39. -17. -55.  32.   8.   6.  52.  99.  -5.  62.]]
[[ 61.  -8. -87.  17.  40.  34.  91. -62. -18.  30.]]
[[-85. -77.   2.  35. -13.  51. -48. -22.  89.  14.]]
[[-80. -82.   6. -35.  29. -18.   0. -15. -39.  95.]]
[[-66.  73.  86.  63.   5. -66.  -5. -35. -66.  14.]]
[[-34.  53. -84. -44. -78.  13.  54. -32. -46. -51.]]
[[-71.  -8.   8.  34. -76.  30.  86.  23.  71.  -5.]]
[[ 76. -27.  37. -66.  14. -21.  81. -54. -29.  61.]]
[[-46. -60. -76. -63.  76.  20. -15.  57. -78.  99.]]
['malicious']
[[ -72.   46.   32.  -70.  -37.   -2.  -97.  -83. -100.  -91.]]
[[ -1.  48.  75.  -6. -96.   8.  92.  81. -28.  50.]]
[[ 82. -80.  -2. -56. -46. -77.  39. -24.  11. -42.]]
[[-78.  78.  13. -73.  59.   2. -19. -73. -27.   1.]]
[[ 91. -67.  48. -80. -40. -15. -58.  69.  36.  84.]]
[[ 91.  94. -84.  19. -11.  42.  37.  -3. -66. -18.]]
[[ -8.  84. -75.  18.  47. -94. -22.  38. -86.   3.]]
[[ 5

In [11]:
df

A     B     C      D     F     G      H     I     j     k
0   -46.0 -60.0 -76.0  -63.0  76.0  20.0  -15.0  57.0 -78.0  99.0
1    46.0 -61.0  79.0  -59.0 -55.0 -36.0 -100.0   7.0 -21.0  58.0
2   -66.0 -45.0 -47.0   32.0 -11.0 -20.0  -92.0  96.0 -96.0  65.0
3    -9.0 -30.0 -26.0  100.0 -99.0 -89.0  -45.0  21.0 -55.0  44.0
4   -77.0 -43.0 -71.0   62.0 -69.0  23.0   15.0 -98.0  28.0  50.0
..    ...   ...   ...    ...   ...   ...    ...   ...   ...   ...
495 -20.0 -74.0 -65.0   89.0 -13.0  99.0  -84.0  96.0 -46.0  97.0
496   9.0  -9.0  22.0   87.0  78.0  80.0   76.0 -29.0  81.0  68.0
497 -87.0 -60.0 -82.0    8.0 -79.0  35.0   13.0 -18.0   5.0  88.0
498 -67.0 -63.0 -59.0   25.0 -35.0  64.0  -11.0  11.0  -9.0  32.0
499 -62.0 -98.0 -34.0   74.0 -19.0  13.0  -49.0   8.0  -4.0  51.0

[500 rows x 10 columns]

In [12]:
df.to_csv('datasets/malicious_data_generated.csv' ,header=False,index=False)

In [ ]:
if(action==0 or action==10 or action==17):
              self.state[0]=round(random.uniform(-0.290698,-133.441860),6)
          elif(action==1 or action==10 or action==17):
               self.state[1]=round(random.uniform(0,1184),6)
          elif(action==2 or action==12 or action==17):
               self.state[2]=round(random.uniform(-0.666667,10.666667),6)
          elif(action==3 or action==12 or action==18):
               self.state[3]=round(random.uniform(-0.312383,109.259173),6)
          elif(action==4 or action==13 or action==18):
               self.state[4]=round(random.uniform(0,30),6)
          elif(action==5 or action==13 or action==18):
               self.state[5]=round(random.uniform(-0.322,127.488889),6)
          elif(action==6 or action==14 or action==18):
               self.state[6]=round(random.uniform(-0.282353,147.976471),6)
          elif(action==7 or action==15 or action==18):
               self.state[7]=round(random.uniform(-0.164688,715.616633),6)
          elif(action==8 or action==15 or action==18):
               self.state[8]=round(random.uniform(-0.324081,106.407677),6)
          else:
               self.state[9]=round(random.uniform(-0.750000,227.5),6)  

        self.length -= 1