In [190]:
import numpy as np
import pandas as pd
import scipy
from collections import OrderedDict
from sklearn import preprocessing
import joblib as jb
import random
import time
from IPython.display import clear_output

In [191]:
#Creando los 10 features y las constantes necesarias
features=['A','B','C','D','F','G','H','I','j','k']


In [192]:
model=jb.load('rfDefense2021.sav')
print(model)

RandomForestClassifier(max_depth=50, n_estimators=250, random_state=45)


In [193]:
#tabla de pandas
df=pd.DataFrame(columns=features)
print(df)

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []


In [194]:
df

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []

In [195]:
def generateValuesV2(malwItems):
    flag=False
    maxLoss=0
    a=0
    valuesToTest=np.array([0,0,0,0,0,0,0,0,0,0])
    
    
    while a<malwItems:   
        
        if flag==False:
          
          valuesToTest=np.array([])
          for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-100,100))
          
          temporalx=valid(valuesToTest,a)  
          a=a+temporalx
          
          if temporalx==1:
            flag=True
            maxLoss=0
            
          
        elif flag==True:
          
          temp=np.array([])
          for x in range(10):
            temp=np.append(temp, random.randint(-2,2))
            
          outarr=np.add(temp,valuesToTest)
          print('enter')
          a=a+valid(outarr,a)
          if(maxLoss==10):
            flag=False
          maxLoss=maxLoss+1
    
    
    

In [196]:
def valid(valuesToTest,a):
    result=None
    val=0
    try:
        result=model.predict(valuesToTest.reshape(1,-1))
        result=np.array2string(result)
        #print(valuesToTest.reshape(1,-1))
    except Exception as ex:
       pass 
    
    if result=="['malicious']":
        print(a+1)
        formatier=valuesToTest.reshape(1,-1)[0]
        df.loc[a]=formatier
        print(formatier)
        val=1
    return val

In [197]:

def generateValues(malwItems):
    
    a=0
    while a<malwItems:
        
        valuesToTest=np.array([])
        result=None
        for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-100,100))
                    
        try:
             result=model.predict(valuesToTest.reshape(1,-1))
             result=np.array2string(result)
             #print(valuesToTest.reshape(1,-1))
        except Exception as ex:
           pass 
        
        if result=="['malicious']":
            
            formatier=valuesToTest.reshape(1,-1)[0]
            df.loc[a]=formatier
            a=a+1
            print(formatier)
            print(a-1)
       

In [198]:

def generateValuesV3(malwItems):
    
    a=0
    while a<malwItems:
        
        valuesToTest=np.array([])
        for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-50,50))
                    
        a=a+valid(valuesToTest,a)

In [199]:
#generateValuesV3(3)

1
[-37. -36. -45. -16.  15.  30. -14.  44. -16.  25.]
2
[  2.  -6.  41.  21.  13.  26.  49. -22.   8.  48.]
3
[-23. -38. -39.  28. -15.   7. -41.  27. -28.  43.]


In [200]:
#generateValues(3)

[-34.   0. -84. -92. -65.  45. -62.  85. -20.  27.]
0
[-68. -27. -42. -86. -83. -69. -46.  14. -70.  30.]
1
[-67. -17. -15.  29. -56.  77. -72.  31. -99.  65.]
2


In [209]:
generateValuesV2(500)

1
[-32. -36. -85.  72. -16. -44.  -9.  35. -60.  85.]
enter
2
[-31. -36. -86.  74. -15. -45. -11.  35. -62.  87.]
enter
3
[-31. -35. -84.  72. -14. -42.  -7.  36. -60.  85.]
enter
4
[-33. -37. -85.  71. -17. -44.  -7.  37. -60.  85.]
enter
5
[-31. -34. -84.  71. -16. -43.  -8.  37. -62.  85.]
enter
6
[-32. -37. -86.  70. -14. -43.  -8.  37. -61.  85.]
enter
7
[-30. -35. -87.  73. -18. -43.  -9.  33. -61.  87.]
enter
8
[-30. -38. -83.  70. -16. -44.  -7.  36. -60.  85.]
enter
9
[-31. -35. -86.  70. -16. -42. -10.  37. -58.  85.]
enter
10
[-34. -36. -86.  71. -14. -43. -10.  35. -61.  84.]
enter
11
[-34. -36. -84.  74. -18. -46. -10.  33. -61.  85.]
enter
12
[-30. -34. -84.  73. -18. -42.  -9.  34. -60.  85.]
13
[-85. -84. -63. -16. -43. -51. -26.  63. -15.  59.]
enter
14
[-87. -84. -65. -14. -45. -50. -25.  61. -14.  57.]
enter
15
[-87. -84. -65. -18. -45. -52. -25.  62. -15.  61.]
enter
16
[-85. -86. -61. -17. -42. -52. -27.  64. -16.  59.]
enter
17
[-84. -82. -62. -14. -42. -52. -28. 

In [202]:
#generateValues(1500)
#clear_output(wait=True)

In [210]:
df

A     B     C     D     F     G     H     I      j     k
0   -32.0 -36.0 -85.0  72.0 -16.0 -44.0  -9.0  35.0  -60.0  85.0
1   -31.0 -36.0 -86.0  74.0 -15.0 -45.0 -11.0  35.0  -62.0  87.0
2   -31.0 -35.0 -84.0  72.0 -14.0 -42.0  -7.0  36.0  -60.0  85.0
3   -33.0 -37.0 -85.0  71.0 -17.0 -44.0  -7.0  37.0  -60.0  85.0
4   -31.0 -34.0 -84.0  71.0 -16.0 -43.0  -8.0  37.0  -62.0  85.0
..    ...   ...   ...   ...   ...   ...   ...   ...    ...   ...
495 -56.0 -54.0 -97.0  83.0 -50.0  75.0  69.0 -14.0   99.0  91.0
496 -56.0 -54.0 -99.0  80.0 -51.0  74.0  68.0 -11.0   98.0  90.0
497 -58.0 -58.0 -96.0  84.0 -48.0  74.0  68.0 -12.0   98.0  91.0
498 -58.0 -58.0 -97.0  83.0 -49.0  76.0  65.0 -11.0  100.0  92.0
499 -55.0 -54.0 -99.0  84.0 -51.0  75.0  69.0 -11.0   99.0  92.0

[500 rows x 10 columns]

In [204]:
df.to_csv('datasets/malicious_data_generated.csv' ,header=False,index=False)