In [2]:
import numpy as np
import pandas as pd
import scipy
from collections import OrderedDict
from sklearn import preprocessing
import joblib as jb
import random
import time
from IPython.display import clear_output

In [3]:
#Creando los 10 features y las constantes necesarias
features=['A','B','C','D','F','G','H','I','j','k']


In [4]:
model=jb.load('rfDefense2021.sav')
print(model)

RandomForestClassifier(max_depth=50, n_estimators=250, random_state=45)


In [5]:
#tabla de pandas
df=pd.DataFrame(columns=features)
print(df)

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []


In [6]:
df

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []

In [7]:
def generateValuesV2(malwItems):
    flag=False
    maxLoss=0
    a=0
    valuesToTest=np.array([0,0,0,0,0,0,0,0,0,0])
    
    
    while a<malwItems:   
        
        if flag==False:
          
          valuesToTest=np.array([])
          for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-100,100))
          
          temporalx=valid(valuesToTest,a)  
          a=a+temporalx
          
          if temporalx==1:
            flag=True
            maxLoss=0
            
          
        elif flag==True:
          
          temp=np.array([])
          for x in range(10):
            temp=np.append(temp, random.randint(-2,2))
            
          outarr=np.add(temp,valuesToTest)
          print('enter')
          a=a+valid(outarr,a)
          if(maxLoss==10):
            flag=False
          maxLoss=maxLoss+1
    
    
    

In [8]:
def valid(valuesToTest,a):
    result=None
    val=0
    try:
        result=model.predict(valuesToTest.reshape(1,-1))
        result=np.array2string(result)
        #print(valuesToTest.reshape(1,-1))
    except Exception as ex:
       pass 
    
    if result=="['malicious']":
        print(a+1)
        formatier=valuesToTest.reshape(1,-1)[0]
        df.loc[a]=formatier
        print(formatier)
        val=1
    return val

In [9]:

def generateValues(malwItems):
    
    a=0
    while a<malwItems:
        
        valuesToTest=np.array([])
        result=None
        for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-100,100))
                    
        try:
             result=model.predict(valuesToTest.reshape(1,-1))
             result=np.array2string(result)
             #print(valuesToTest.reshape(1,-1))
        except Exception as ex:
           pass 
        
        if result=="['malicious']":
            
            formatier=valuesToTest.reshape(1,-1)[0]
            df.loc[a]=formatier
            a=a+1
            print(formatier)
            print(a-1)
       

In [10]:

def generateValuesV3(malwItems):
    
    a=0
    while a<malwItems:
        
        valuesToTest=np.array([])
        for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-50,50))
                    
        a=a+valid(valuesToTest,a)

In [11]:
#generateValuesV3(3)

In [12]:
#generateValues(3)

In [13]:
generateValuesV2(1000)

1
[ -22.   98. -100.   66.  -80.   91.   63.    1.   86.  100.]
enter
enter
2
[ -20.   99. -101.   67.  -81.   93.   61.    0.   84.  100.]
enter
3
[-21.  99. -98.  64. -78.  93.  61.   1.  86. 100.]
enter
4
[ -24.   98. -102.   67.  -78.   89.   64.    3.   88.   98.]
enter
5
[-22.  99. -98.  64. -81.  91.  62.   0.  88.  99.]
enter
6
[ -23.   96. -101.   65.  -78.   90.   64.    2.   85.  102.]
enter
7
[ -23.   96. -101.   67.  -82.   91.   62.    2.   85.   98.]
enter
8
[-23. 100. -99.  68. -78.  92.  63.   3.  85.  99.]
enter
enter
enter
9
[ -20.   99. -100.   68.  -82.   93.   61.    3.   86.   98.]
10
[-69. -57. -12.  -2. -36.  16. -32.  96. -55.  15.]
enter
enter
11
[-69. -59. -13.  -3. -37.  14. -33.  97. -56.  15.]
enter
enter
12
[-71. -58. -14.  -2. -36.  17. -30.  97. -55.  16.]
enter
13
[-67. -59. -11.  -4. -38.  17. -31.  98. -53.  16.]
enter
14
[-70. -59. -11.  -2. -36.  18. -31.  94. -55.  14.]
enter
15
[-69. -55. -11.  -3. -37.  17. -34.  95. -53.  14.]
enter
16
[-68. -

In [14]:
#generateValues(1500)
#clear_output(wait=True)

In [15]:
df

A     B      C     D     F     G     H     I     j      k
0   -22.0  98.0 -100.0  66.0 -80.0  91.0  63.0   1.0  86.0  100.0
1   -20.0  99.0 -101.0  67.0 -81.0  93.0  61.0   0.0  84.0  100.0
2   -21.0  99.0  -98.0  64.0 -78.0  93.0  61.0   1.0  86.0  100.0
3   -24.0  98.0 -102.0  67.0 -78.0  89.0  64.0   3.0  88.0   98.0
4   -22.0  99.0  -98.0  64.0 -81.0  91.0  62.0   0.0  88.0   99.0
..    ...   ...    ...   ...   ...   ...   ...   ...   ...    ...
995 -98.0 -39.0  -33.0 -10.0  59.0   2.0 -30.0  85.0 -14.0   79.0
996 -99.0 -36.0  -33.0  -9.0  59.0   1.0 -30.0  83.0 -16.0   79.0
997 -97.0 -39.0  -36.0 -10.0  63.0   3.0 -30.0  83.0 -17.0   77.0
998 -99.0 -38.0  -34.0  -7.0  59.0   1.0 -29.0  87.0 -15.0   78.0
999 -97.0 -37.0  -33.0  -6.0  62.0   0.0 -29.0  87.0 -14.0   78.0

[1000 rows x 10 columns]

In [16]:
df.to_csv('datasets/malicious_data_generated.csv' ,header=False,index=False)