In [12]:
import numpy as np
import pandas as pd
import scipy
from gym import error, spaces, utils
from collections import OrderedDict
from sklearn import preprocessing
import joblib as jb
import random
import time

In [13]:
#Creando los 10 features y las constantes necesarias
features=['A','B','C','D','F','G','H','I','j','k']
n_states=len(features)
n_actions=500
e = 0.9 # greedy factor
a= 0.1  # learning rate
g= 0.9 # discount factor
max_episodes = 3 # maximum episodes
fresh_time= 0.3 # fresh time for one move

In [14]:
model=jb.load('rfDefense2021.sav')
print(model)

RandomForestClassifier(max_depth=50, n_estimators=250, random_state=45)


In [15]:
#tabla de pandas
df=pd.DataFrame(columns=features)
print(df)

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []


In [16]:
df

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []

In [17]:



def generateValues(malwItems):
    a=0
    while a<malwItems:
        
        valuesToTest=np.array([])
        result=None
        for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-100,100))
                    
        try:
             result=model.predict(valuesToTest.reshape(1,-1))
             result=np.array2string(result)
             print(valuesToTest.reshape(1,-1))
        except Exception as ex:
           pass 
        
        if result=="['malicious']":
            formatier=valuesToTest.reshape(1,-1)[0]
            df.loc[a]=formatier
            a=a+1
            print(result)
       

In [18]:
generateValues(500)

[[ 12.  91. -33.  45.  51. -85.  86. -35.  15. -59.]]
[[ -9.  -1.  23.  21. -54. -87. -71. -65. -36.  94.]]
[[-88.   1. -96. -12. -81. -65. -71.  79.  58.  75.]]
[[ 95. -53.  61. -73. -52. -55.  11. -35.  71.  22.]]
[[ 80. -74.  90. -35.  97. -14. -47.  43. -45.  70.]]
[[ 88.  77. -61.  45. -67. -74.  14. -71.  90. -23.]]
[[ 69.  57.  45. -91.  61. -59.  12.  16.  43. -94.]]
[[ 57. -32.  51.   1.  85.  21. -72. -41. -83.  -6.]]
[[-42.  73. -35.  99.  98. -61. -53.  50.  83. -18.]]
[[ 67.  33. -92. -34. -68. -78. -59.  91.  28.  24.]]
[[ 88.  44.  89.  -5. -19. -56.  54.  27.  32.  95.]]
[[ 41. -12.  64. -55.  -2. -41.  28.  62. -50. -54.]]
[[ 49.  59. -37. -58. -11. -10. -30. -17.  -3. -40.]]
[[-91.  93.  56. -90.  35.  15. -75.  -4.  -9.   5.]]
[[-60. -74. -57.  10.   2. -31. -73.  12. -76.  26.]]
[[ -9.   0.  10.  77.  -3.  14. -64. -30. -84. -28.]]
[[-76.  51.  74.   6. -27.  11. -43.  41. -20. -73.]]
[[ 78. -95. -19.  71.  90.  79. -34.  19. -93.  12.]]
[[-99. -32. -13. -89. -27.  

In [19]:
df

A     B     C      D     F     G     H     I     j     k
0   -99.0 -16.0 -73.0  -84.0 -59.0 -11.0  -6.0   6.0 -41.0  23.0
1   -60.0 -35.0 -35.0  -69.0  73.0  61.0 -62.0  82.0 -44.0  59.0
2    31.0  57.0 -11.0  -44.0  11.0  44.0 -89.0  17.0   6.0  69.0
3   -59.0  -9.0 -85.0  -60.0 -28.0 -73.0 -78.0  12.0 -72.0  75.0
4   -13.0 -19.0 -50.0 -100.0 -48.0 -64.0 -54.0  58.0 -71.0   1.0
..    ...   ...   ...    ...   ...   ...   ...   ...   ...   ...
495  37.0  36.0 -25.0  -59.0 -86.0  59.0 -20.0  30.0   5.0  59.0
496 -96.0  48.0 -81.0   73.0 -54.0  24.0  44.0 -51.0  34.0  82.0
497 -83.0 -35.0 -81.0   82.0  -1.0  43.0  46.0 -22.0  50.0  88.0
498 -57.0 -13.0 -99.0  -84.0 -47.0 -15.0 -92.0  49.0 -28.0  37.0
499 -34.0  16.0  -5.0   18.0 -15.0  68.0 -61.0   1.0  41.0  27.0

[500 rows x 10 columns]

In [20]:
df.to_csv('datasets/malicious_data_generated.csv' ,header=False,index=False)